#!/bin/sh

sub_help () {

  echo
  echo "COMMANDS:"
  echo
  echo "  query"
  echo "    - all      (View all running queries)"
  echo "    - long     (Queries running for longer than five minutes)"
  echo "    - kill     (Kill query by pid)"
  echo "    - killall  (Kill all queries)"
  echo
  echo "  index"
  echo "    - info     (Show general usage)"
  echo "    - missing  (Missing indexes)"
  echo "    - unused   (Unused indexed)"
  echo
  echo "  space        (Show largest tables and indexes)"
  echo
  echo "  cache"
  echo "    - index    (Index hit rate)"
  echo "    - table    (Table hit rate)"
  echo
  echo "  install      (Install pghero)"
  echo "  uninstall    (Uninstall pghero)"
  echo
  echo "Note: all additional parameters are passed on to psql"
  echo
}

_exec_and_display () {
  local query="$1"
  shift
  psql -c "$query" $@
}


# INSTALL
sub_install () {
  curl https://raw.githubusercontent.com/ankane/pghero.sql/master/install.sql | psql $@
}

# UNINSTALL
sub_uninstall () {
  curl https://raw.githubusercontent.com/ankane/pghero.sql/master/uninstall.sql | psql $@
}

# QUERY
sub_query_running () {
  local query="SELECT * FROM pghero_running_queries;"
  _exec_and_display "$query" $@
}

sub_query_long_running () {
  local query="SELECT * FROM pghero_long_running_queries;"
  _exec_and_display "$query" $@
}

sub_query_kill () {
  local query_pid=$1
  if ! [ "$(echo $query_pid | grep "^[ [:digit:] ]*$")" ]; then
    echo "'$query_pid' is not a valid pid"
    exit 1
  fi
  local query="SELECT pghero_kill(${query_pid});"
  _exec_and_display "$query" $@
}

sub_query_killall () {
  local query="SELECT pghero_kill_all();"
  _exec_and_display "$query" $@
}

sub_query () {
  local s_cmd=$1
  case $s_cmd in
    "a" | "all")
      shift
      sub_query_running $@
      ;;
    "l" | "long")
      shift
      sub_query_long_running $@
      ;;
    "k" | "kill")
      shift
      sub_query_kill $@
      ;;
    "ka" | "killall")
      shift
      sub_query_killall $@
      ;;
    *)
      echo "'$s_cmd' is not a valid subcommand"
      sub_help
      ;;
  esac
}

# INDEX
sub_index_info () {
  local query="SELECT * FROM pghero_index_usage;"
  _exec_and_display "$query" $@
}

sub_index_missing () {
  local query="SELECT * FROM pghero_missing_indexes;"
  _exec_and_display "$query" $@
}

sub_index_unused () {
  local query="SELECT * FROM pghero_unused_indexes;"
  _exec_and_display "$query" $@
}

sub_index () {
  local s_cmd=$1
  case $s_cmd in
    "i" | "info")
      shift
      sub_index_info $@
      ;;
    "m" | "missing")
      shift
      sub_index_missing
      ;;
    "u" | "unused")
      shift
      sub_index
      ;;
    *)
      echo "'$s_cmd' is not a valid command"
      sub_help
      ;;
  esac
}

# SPACE 
sub_space () {
  local query="SELECT * FROM pghero_relation_sizes;"
  _exec_and_display "$query" $@
}

# CACHE
sub_cache_index () {
  local query="SELECT pghero_index_hit_rate();"
  _exec_and_display "$query" $@
}

sub_cache_table () {
  local query="SELECT pghero_table_hit_rate();"
  _exec_and_display "$query" $@
}

sub_cache () {
  local s_cmd=$1
  case $s_cmd in
    "i" | "index")
      shift
      sub_cache_index $@
      ;;
    "t" | "table")
      shift
      sub_cache_table $@
      ;;
    *)
      echo "'$s_cmd' is not a valid command"
      sub_help
  esac
}

s_cmd=$1
case $s_cmd in
  "" | "h" | "help")
    sub_help
    ;;
  "q" | "query" | "queries")
    shift
    sub_query $@
    ;;
  "s" | "space")
    shift
    sub_space $@
    ;;
  "i" | "index")
    shift
    sub_index $@
    ;;
  "c" | "cache")
    shift
    sub_cache $@
    ;;
  "install")
    shift
    sub_install $@
    ;;
  "uninstall")
    shift
    sub_uninstall $@
    ;;
  *)
    echo "'$s_cmd' is not a valid command"
    sub_help
    ;;
esac
