#!/bin/sh

sub_help () {
  echo
  echo "USAGE:"
  echo
  echo "  pghero [COMMAND] [SUBCOMMAND] [PSQL OPTIONS]... "
  echo
  echo "COMMANDS:"
  echo 
  echo "  help      - Show this help text"
  echo "  space     - Show largest tables and indexes"
  echo "  install   - Install pghero"
  echo "  uninstall - Uninstall pghero"
  echo
  echo "  query:"
  echo "    all     - View all running queries"
  echo "    long    - Queries running for longer than five minutes"
  echo "    kill    - Kill query by pid"
  echo "    killall - Kill all queries"
  echo
  echo "  index:"
  echo "    usage   - Show general usage"
  echo "    missing - Missing indexes"
  echo "    unused  - Unused indexed"
  echo
  echo "  cache:"
  echo "    index   - Index hit rate"
  echo "    table   - Table hit rate"
  echo
  echo "Note: all additional parameters are passed on to psql"
  echo
  echo "EXAMPLES:"
  echo
  echo "  > pghero install -W"
  echo "  > pghero query all"
  echo "  > pghero space -d <database> -U <user>"
  echo
}

_invalid_sub () {
  echo "'$1' is not a valid command" >&2
  sub_help
  exit 1
}

_exec_and_display () {
  local query="$1"
  shift
  psql -c "$query" $@
}


# INSTALL
sub_install () {
  curl https://raw.githubusercontent.com/ankane/pghero.sql/master/install.sql | psql $@
}

# UNINSTALL
sub_uninstall () {
  curl https://raw.githubusercontent.com/ankane/pghero.sql/master/uninstall.sql | psql $@
}

# QUERY
sub_query () {
  local sub=$1
  shift
  case $sub in
    "a" | "all")
      _exec_and_display "SELECT * FROM pghero_running_queries;" $@
      ;;
    "l" | "long")
      _exec_and_display "SELECT * FROM pghero_long_running_queries;" $@
      ;;
    "k" | "kill")
      local query_pid=$1
      if ! [ "$(echo $query_pid | grep "^[ [:digit:] ]*$")" ]; then
        echo "'$query_pid' is not a valid pid"
        exit 1
      fi
      shift
      _exec_and_display "SELECT pghero_kill(${query_pid});" $@
      ;;
    "ka" | "killall")
      _exec_and_display "SELECT pghero_kill_all();" $@
      ;;
    *)
      _invalid_sub "$sub"
      ;;
  esac
}

# INDEX
sub_index () {
  local sub=$1
  shift
  case $sub in
    "u" | "usage")
      _exec_and_display "SELECT * FROM pghero_index_usage;" $@
      ;;
    "m" | "missing")
      _exec_and_display "SELECT * FROM pghero_missing_indexes;" $@
      ;;
    "un" | "unused")
      _exec_and_display "SELECT * FROM pghero_unused_indexes;" $@
      ;;
    *)
      _invalid_sub "$sub"
      ;;
  esac
}

# SPACE 
sub_space () {
  _exec_and_display "SELECT * FROM pghero_relation_sizes;" $@
}

# CACHE
sub_cache () {
  local sub=$1
  shift
  case $sub in
    "i" | "index")
      _exec_and_display "SELECT pghero_index_hit_rate();" $@
      ;;
    "t" | "table")
      _exec_and_display "SELECT pghero_table_hit_rate();" $@
      ;;
    *)
      _invalid_sub "$sub"
  esac
}

# MAIN
_main () {
  local sub=$1
  case $sub in
    "" | "h" | "-h" | "help" | "--help")
      sub_help
      ;;
    *)
      shift
      if type sub_${sub} | grep -i function > /dev/null; then
        sub_${sub} $@
      else
        _invalid_sub $sub
      fi
      ;;
  esac
}

_main $@
